# Generated by Django 2.0.3 on 2018-03-23 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quibble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 3, 23, 17, 57, 45, 330488, tzinfo=utc), editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quibbles_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
