# Generated by Django 2.0.3 on 2018-03-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordplay', '0003_auto_20180323_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quibble',
            old_name='user_id',
            new_name='user',
        ),
    ]
