# Generated by Django 2.0.3 on 2018-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordplay', '0004_auto_20180323_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='quibble',
            name='status',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
