# Generated by Django 2.0.3 on 2018-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordplay', '0005_quibble_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quibble',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('M', 'Modified')], default='C', max_length=1),
        ),
    ]
